BLOG_FOLDER_ID = '0Byj8ccoezKFWNVFNb0RTSEZfcGs'
BLOG_USER_ID = 'akiva.bamberger'
BLOG_TITLE = 'rm -rf /'
BLOG_IMAGE = '/r/images/me.jpg'
BLOG_SNIPPET = 'thoughts and projects by akiva'
DISQUS_ID = 'rmrf'
GOOGLE_ANALYTICS_ID = 'UA-xxxxxxxx-1'
GOOGLE_ANALYTICS_SITE = 'rm-rfslash.appspot.com'
